// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteTeamMember struct {
	TeamMemberID string `json:"teamMemberId"`
}

type NewTeamMember struct {
	Name string `json:"name"`
	Role string `json:"role"`
	City string `json:"city"`
}

type TeamMember struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
	City string `json:"city"`
}

type UpdateTeamMember struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
	Role *string `json:"role"`
	City *string `json:"city"`
}
